// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package processor

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	migrationProcessorConfigBooleanFields = "boolean_fields"
)

func (migrationProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		migrationProcessorConfigBooleanFields: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
