// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package processor

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	migrationProcessorConfigCollections = "collections"
	migrationProcessorConfigPostgresDsn = "postgres_dsn"
)

func (migrationProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		migrationProcessorConfigCollections: {
			Default:     "",
			Description: "Collections is a list of allowed collections.\nUnknown collections passed in processor will trigger an error",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		migrationProcessorConfigPostgresDsn: {
			Default:     "",
			Description: "DSN is required to understand set fields allowed values.\n\nFormat: scheme://username:password@host:port/dbname?param1=value1&param2=value2&...",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
