// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package processor

import (
	"regexp"

	"github.com/conduitio/conduit-commons/config"
)

const (
	migrationProcessorConfigCollectionsBooleanFields   = "collections.*.boolean_fields"
	migrationProcessorConfigCollectionsSetFields       = "collections.*.set_fields"
	migrationProcessorConfigCollectionsTimestampFields = "collections.*.timestamp_fields"
	migrationProcessorConfigMysqlDbDsn                 = "mysql_db_dsn"
)

func (migrationProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		migrationProcessorConfigCollectionsBooleanFields: {
			Default:     "",
			Description: "BooleanFields is a list of references to collection boolean fields.\nThis fields will be converted into boolean using\n[strconv.ParseBool](https://pkg.go.dev/strconv#ParseBool) method.\n\nReferences should be separated with comma.\nExample: .Payload.After.field_a, .Payload.After.field_b\n\nFor more information about the format,\nsee [Referencing fields](https://conduit.io/docs/using/processors/referencing-fields).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		migrationProcessorConfigCollectionsSetFields: {
			Default:     "",
			Description: "SetFields is a list of references to collection fields of type Set.\n[Mysql connector](https://github.com/conduitio-labs/conduit-connector-mysql)\nrepresents values of type Set as a comma-separated strings.\nPostgres requires brackets around a value.\n\nReferences should be separated with comma.\nExample: .Payload.After.field_a, .Payload.After.field_b\n\nFor more information about the format,\nsee [Referencing fields](https://conduit.io/docs/using/processors/referencing-fields).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		migrationProcessorConfigCollectionsTimestampFields: {
			Default:     "",
			Description: "TimestampFields is a list of references to collection fields of type\nTimestamp.\nThis processor is required for legacy MySQL v5.5 which supports\nzero-timestamps (0000-00-00 00:00:00).\n[Mysql connector](https://github.com/conduitio-labs/conduit-connector-mysql)\nconverts this kink of timestamps into golang 0-timestamp (0001-01-01 00:00:00).\nIt should be represented into null-values in Postgres.\n\nReferences should be separated with comma.\nExample: .Payload.After.field_a, .Payload.After.field_b\n\nFor more information about the format,\nsee [Referencing fields](https://conduit.io/docs/using/processors/referencing-fields).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		migrationProcessorConfigMysqlDbDsn: {
			Default:     "",
			Description: "DSN is required to understand set fields allowed values.\nTODO: move this logic in config: at now configuration too\ndifficult from paramgen restrictions",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationRegex{Regex: regexp.MustCompile("^[^:]+:.*@tcp\\([^:]+:\\d+\\)/\\S+")},
			},
		},
	}
}
